### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by davyk7** [syneo-tools-gmbh/Javascript-BCR-Library#2]
Thanks for your job !

**Comment by renzosala** [comment]
Hi vYk,
You’re right in my last commit I let the index.html pre-set on the sample ocr.js, which I used to debug the Google Vision part (only used in a mobile context).
I will fix it right now (changing the ocr engine used in the initialize done in the index.js of the sample app to ocrEngine.TESSERACT and removing the sampleOcr parameter in the recognize call)

Sample/index.html
bcr.recognize(b64, displayResult, displayProgress);

Sample/js/index.js
await bcr.initialize(ocrEngines.TESSERACT, cropStrategy.SMART, languages.ENGLISH, 2160, 1440, false, true);

best regards
Renzo
